name: Build Docker

on:
  push:
    branches:
      - 'main'                  # main 브랜치에서만 실행
    paths:
      - 'requirements.txt'      # requirements.txt 파일이 변경되었을 때
      - 'Dockerfile'             # Dockerfile 파일이 변경되었을 때
      - 'docker-compose.yaml'    # docker-compose.yaml 파일이 변경되었을 때
  pull_request:
    branches:
      - 'main'                  # main 브랜치에서만 실행
    paths:
      - 'requirements.txt'      # requirements.txt 파일이 변경되었을 때
      - 'Dockerfile'             # Dockerfile 파일이 변경되었을 때
      - 'docker-compose.yaml'    # docker-compose.yaml 파일이 변경되었을 때
  
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/requirements.txt', '**/docker-compose.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
            
      # Docker 이미지 빌드
      - name: Build Docker image using Docker Compose
        run: |
          echo "Starting Docker Compose build..."
          docker-compose build 
          echo "Docker Compose build completed."

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에 저장된 Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에 저장된 Docker Hub password or token

      # Docker 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker tag my-airflow ${{ secrets.DOCKER_USERNAME }}/my-airflow:latest  # 이미지에 태그를 추가
          docker push ${{ secrets.DOCKER_USERNAME }}/my-airflow:latest  # Docker Hub에 푸시
          echo "Docker image pushed successfully."

      # 이미지 테스트 (예: 이미지 확인)
      - name: Verify Docker image
        run: |
          echo "Verifying Docker image..."
          docker images | grep my-airflow || echo "Docker image not found!"
          echo "Docker image verification completed."

      # 설치된 패키지 확인
      - name: List installed packages
        run: |
          echo "Listing installed packages..."
          docker run --rm my-airflow pip list || echo "No packages found!"
          echo "Package listing completed."
