name: CI/CD Pipeline with VPN and Self-hosted Runner

on:
  push:
    branches:
      - master  # main 브랜치에 코드가 푸시될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # self-hosted runner에서 실행
    steps:
      
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. GPU 서버로 배포 (SSH를 통해 배포)
      - name: Deploy to GPU server
        run: |
          ssh -i jjs_490.pem -p 32643 root@10.196.197.2 << EOF
            # GPU 서버에서 배포 작업 실행
            cd /data/ephemeral/home
            # 예시로 배포 스크립트를 실행
            ./deploy.sh
            echo "배포 완료"  # 확인용
          EOF

      # 4. 테스트 실행 (필요시 테스트를 수행)
      - name: Run tests
        run: |
          pytest tests/

