name: CI/CD Pipeline with VPN and Self-hosted Runner

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 푸시될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # self-hosted runner에서 실행
    steps:
      
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
        
      # 2. VPN 연결 (예: OpenVPN을 사용하여 VPN 연결)
      - name: Connect to VPN
        run: |
          echo "$VPN_CONFIG" > "C:\Users\edu\Downloads\openvpn01-TCP4-1188-config.ovpn"  # VPN 설정을 GitHub Secrets에서 가져오기
          "C:\Program Files\OpenVPN\bin\openvpn.exe" --config "C:\Users\edu\Downloads\openvpn01-TCP4-1188-config.ovpn" --daemon
  # VPN 연결
      
      # 3. GPU 서버에서 실행
      - name: Deploy to GPU server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p 32643 root@10.196.197.2 << EOF
            # GPU 서버에서 작업 실행
            cd /data/ephemeral/home
            echo "Hello from GitHub Actions!" > github_actions_test.txt
          EOF

      # 4. 테스트 실행 (필요시 테스트를 수행)
      - name: Run tests
        run: |
          pytest tests/

