name: CI/CD Pipeline with VPN

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 푸시될 때 실행

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start OpenVPN with Admin Rights
        run: |
          start "" "C:\Program Files\OpenVPN\bin\openvpn.exe" --config "C:\Users\openvpn01-TCP4-1188-config.ovpn" --auth-user-pass "C:\Users\vpn-auth.txt" --daemon
        shell: cmd

      - name: Get most recent file
        run: |
          # 가장 최근에 푸시된 파일을 찾기 위해 git 명령어 사용
          latest_file=$(git diff --name-only HEAD~1..HEAD)
          echo "Most recent file: $latest_file"
          
          # 해당 파일을 GPU 서버로 복사
          scp -i "C:\Users\jjs_490.pem" -P 32643 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $latest_file root@10.196.197.2:/data/ephemeral/home/
        shell: cmd
