name: CI/CD Pipeline with VPN

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 푸시될 때 실행
      
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start OpenVPN with Admin Rights
        run: |
          start "" "C:\Program Files\OpenVPN\bin\openvpn.exe" --config "C:\Users\openvpn01-TCP4-1188-config.ovpn" --auth-user-pass "C:\Users\vpn-auth.txt" --daemon
        shell: cmd


      - name: Deploy to GPU server
        run: |
          ssh -i "C:\Users\jjs_490.pem" -p 32643 root@10.196.197.2 "cd /data/ephemeral/home && echo 'Hello from GitHub Actions!' > github_actions_test.txt"
        shell: cmd
