name: Run Airflow Container

on:
  workflow_run:
    workflows: ["Build Docker"]  # Build_Docker.yml이 끝난 후 실행
    types:
      - completed  # Build Docker가 완료되면 실행
  workflow_dispatch:           # 수동으로 실행

jobs:
  run-airflow-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Compose 설치 (필요한 경우)
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Docker Compose로 Airflow 컨테이너 실행
      - name: Run Airflow container using Docker Compose
        run: |
          docker network create mlops_network  # network create
          docker-compose up -d  # 컨테이너 실행
          sleep 30  # 컨테이너가 정상적으로 실행되도록 대기

      # 모든 컨테이너 상태 확인
      - name: Verify all containers
        run: |
          docker ps -a  # 모든 컨테이너 상태 출력
          echo "All containers are listed."

      # Airflow DAGs 목록 확인
      - name: List Airflow DAGs
        run: |
          sleep 30  # 30초 대기
          docker exec action_practice_airflow-webserver_1 airflow dags list || echo "Failed to list DAGs."
          echo "Airflow DAGs listed."

