name: Run Airflow Container

on:
  workflow_run:
    workflows: ["Build Docker"]  # Build_Docker.yml이 끝난 후 실행
    types:
      - completed  # Build Docker가 완료되면 실행
  workflow_dispatch:           # 수동으로 실행

jobs:
  run-airflow-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Hub에서 이미지 가져오기
      - name: Run Airflow container from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-airflow  
          docker run -d -p 8080:8080 --name my-airflow ${{ secrets.DOCKER_USERNAME }}/my-airflow
          sleep 30

      # Airflow 컨테이너 상태 확인
      - name: Verify Airflow container
        run: |
          docker ps -a | grep my-airflow || echo "Airflow container not found!"
          echo "Airflow container is running."
