name: Stop Airflow Container

on:
  workflow_dispatch:           # 수동으로 실행

jobs:
  stop-airflow-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 컨테이너 중지
      - name: Stop Airflow container using Docker Compose
        run: |
          cd action_practice 
          docker-compose stop || echo "Container not found or Docker Compose is not set up!"
          echo "Airflow container stopped using Docker Compose."
