name: Stop Airflow Container

on:
  workflow_dispatch:           # 수동으로 실행

jobs:
  stop-airflow-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 컨테이너 종료
      - name: Stop Airflow container
        run: |
          docker stop my-airflow || echo "Airflow container not found!"
          echo "Airflow container stopped."
