name: Trigger Airflow DAG NOT USE

on:
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  trigger-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Airflow DAG
        run: |
          curl -X POST "172.18.0.4:8080/api/v1/dags/example_dag_decorator/dagRuns" \
          -H "Content-Type: application/json" \
          -u "admin:admin" \
          -d '{"start_date": "2025-01-20"}'
