name: Trigger Airflow DAG

on:
  workflow_run:
    workflows: ["Run Airflow Container"]  # 이전 워크플로우 실행 후 트리거
    types:
      - completed  # "Run Airflow Container"가 완료되면 실행
  workflow_dispatch:  # 수동으로 실행

jobs:
  trigger-airflow-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Airflow DAG 트리거
      - name: Trigger DAG in Airflow
        run: |
          docker exec my-airflow airflow dags trigger -d book_recommendation_pipeline || echo "Failed to trigger DAG."

      # 로그 가져오기 (DAG 실행 로그 예시)
      - name: Fetch logs for DAG task
        run: |
          docker exec my-airflow airflow logs book_recommendation_pipeline task_name --start-date 2025-01-01 --end-date 2025-01-02
          echo "Logs fetched successfully."

          
