name: Trigger Airflow DAG

on:
  workflow_run:
    workflows: ["Run Airflow Container"]  # 이전 워크플로우 실행 후 트리거
    types:
      - completed  # "Run Airflow Container"가 완료되면 실행
  workflow_dispatch:  # 수동으로 실행

jobs:
  trigger-airflow-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Airflow DAG 트리거
      - name: Trigger DAG in Airflow
        run: |
          docker exec action_practice_airflow-webserver_1 airflow dags trigger -d book_mlops || echo "Failed to trigger DAG."

      # 로그 출력
      - name: Fetch Airflow logs
        run: |
          docker logs action_practice_airflow-webserver_1 2>&1 | grep "Recommended books" || echo "Log message not found"
